name: Deploy Next.js to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies
      - name: 📦 Install dependencies
        run: npm ci

      # 4️⃣ Create env file
      - name: 🔐 Create .env.production
        run: |
          echo "NODE_ENV=production" > .env.production
          echo "NEXT_PUBLIC_SITE_URL=https://tstourtravels.com" >> .env.production
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env.production
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env.production
          echo "AUTH_URL=https://tstourtravels.com" >> .env.production
          echo "AUTH_URL_INTERNAL=http://localhost:3000" >> .env.production
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env.production
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env.production
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env.production

      # 5️⃣ Build
      - name: 🏗️ Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production

      # 6️⃣ Prepare deploy
      - name: 📂 Prepare deployment files
        run: |
          mkdir -p deploy

          # Standalone files
          cp -r .next/standalone/* deploy/

          # Complete .next folder
          cp -r .next deploy/.next

          # Public assets
          if [ -d public ]; then
            cp -r public deploy/public
          fi

          # Required files
          cp .env.production deploy/.env
          cp package.json deploy/
          cp package-lock.json deploy/

          echo "✅ Deployment ready"

      # 7️⃣ Upload to cPanel
      - name: 🚀 Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/
          server-dir: ./
          protocol: ftp
          port: 21
          dangerous-clean-slate: false

      # 8️⃣ Done
      - name: ✅ Deployment Complete
        run: |
          echo "================================================"
          echo "✅ CODE UPLOADED SUCCESSFULLY!"
          echo "================================================"
          echo ""
          echo "🔧 FINAL STEPS (in cPanel):"
          echo ""
          echo "1. Login to cPanel"
          echo "2. Go to: Setup Node.js App"
          echo "3. Click: 'Run NPM Install' button"
          echo "4. Wait ~2-3 minutes"
          echo "5. Click: 'Restart' button"
          echo "6. Done! 🎉"
          echo ""
          echo "Your site: https://tstourtravels.com"
          echo "================================================"